[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pacman42"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = "==3.11.16"
authors = [
    { name = "ecarabal", email = "ecarabal@student.codam.nl" },
	{ name = "kfletter", email = "kfletter@student.codam.nl" }
]

[tool.mypy]
files = ["src"]
ignore_missing_imports = true
strict = false # Optional: enforces strict typing


[tool.flake8]
files = ["src"]
max-line-length = 127
exclude = [".git", "__pycache__", "build", "dist"]
select = ["E9", "F63", "F7", "F82", "E", "W", "F"]

[dependency-groups]
req = [
	"python-dotenv==1.2.2",
    "maze-generator",
    "minilibx"
]

dev = [
    "uv==0.12.5",
]

linters = [
    "flake8==7.0.0",
    "mypy==1.9.0",
]

test = [
    "pytest>=8.0.0",
]

[tool.uv.sources]
maze-generator = { path = "./src/wheels/mazegenerator-00001-py3-none-any.whl" }
minilibx = { path = "./src/wheels/minilibx/mlx-2.2-py3-ubuntu-any.whl" }

[tool.setuptools.packages.find]
where = ["src"]
