name: Code Quality (Linting)

on:
  #push:
  #  branches-ignore:
  #    - master
  pull_request:
    branches:
      - development
    paths:
      - '.github/workflows/enforce-formatting.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: "3.11"
          enable-cache: true
      - name: Install Selected Dependencies
        run: uv sync --group linters --group req
      - name: Run Flake8 Linter
        run: uv run flake8
      - name: Run Mypy Type Checker
        run: uv run mypy
